package dotenv

import (
	"bytes"
	"encoding/base64"
	"testing"
)

// Known-answer vectors generated by the web app (the source of truth) via
// App\Services\EncryptionService::encryptWithProjectKey. They lock the
// cross-language crypto contract: a project key is a RAW STRING (never
// hex/base64-decoded), used as ASCII bytes padded with '0' (0x30) or truncated
// to 32 bytes for AES-256-GCM, wire format base64(IV[12] + ciphertext + tag[16]).
//
// Regenerate from the web if the contract ever changes:
//
//	php artisan tinker --execute='echo app(App\Services\EncryptionService::class)
//	  ->encryptWithProjectKey("HELLO=world\nFOO=bar", "<key>");'
var webCryptoVectors = []struct {
	name       string
	key        string
	ciphertext string
	plaintext  string
}{
	{
		name:       "hex64_key_truncated_to_32_chars",
		key:        "52c7e8f043e61267076c35827d6c4be454c70ecac00bf10e79a56d703e32e123",
		ciphertext: "7GvE2YvXvWsbzoQ71OocEa3yGvCdWf2hFTz6goD6f3xRBpLnZeS84QoisjblDTY=",
		plaintext:  "HELLO=world\nFOO=bar",
	},
	{
		name:       "short_key_padded_with_zero",
		key:        "test-key-123",
		ciphertext: "+zDYe4BoH2laQAU8AUyFVFHiZ8S5pnY6Ysk8EaeU5DvVPFjJ6Sm+CsztAgHin3w=",
		plaintext:  "HELLO=world\nFOO=bar",
	},
}

func TestDecryptWebVectors(t *testing.T) {
	for _, tc := range webCryptoVectors {
		t.Run(tc.name, func(t *testing.T) {
			got, err := DecryptWithProjectKey(tc.ciphertext, tc.key)
			if err != nil {
				t.Fatalf("DecryptWithProjectKey(%s): %v", tc.name, err)
			}
			if got != tc.plaintext {
				t.Fatalf("got %q, want %q", got, tc.plaintext)
			}
		})
	}
}

func TestProjectKeyRoundTrip(t *testing.T) {
	for _, tc := range webCryptoVectors {
		t.Run(tc.name, func(t *testing.T) {
			ct, err := EncryptWithProjectKey("SECRET=value", tc.key)
			if err != nil {
				t.Fatalf("EncryptWithProjectKey: %v", err)
			}
			pt, err := DecryptWithProjectKey(ct, tc.key)
			if err != nil {
				t.Fatalf("DecryptWithProjectKey: %v", err)
			}
			if pt != "SECRET=value" {
				t.Fatalf("round-trip got %q, want %q", pt, "SECRET=value")
			}
		})
	}
}

// TestDeriveDataKeyVector locks the client-managed data-key KDF contract
// (PBKDF2-HMAC-SHA256, raw passphrase, 32-byte output) to a vector computed
// independently of this code:
//
//	python3 -c 'import hashlib,base64; \
//	  print(base64.b64encode(hashlib.pbkdf2_hmac("sha256", \
//	  b"correct horse battery staple", bytes(range(16)), 1000, 32)).decode())'
//
// The browser's EncryptionUtils.deriveDataKey (WebCrypto PBKDF2) must produce
// the same bytes for the same passphrase/salt/iterations, or CLI and browser
// cannot decrypt each other's client-managed secrets.
func TestDeriveDataKeyVector(t *testing.T) {
	saltB64 := "AAECAwQFBgcICQoLDA0ODw==" // bytes 0x00..0x0f
	wantB64 := "ppsXnjrdPB4KryJ6DrOqKqhkWrhv7PbKAMF1Eml8cZ4="

	got, err := DeriveDataKey("correct horse battery staple", saltB64, 1000)
	if err != nil {
		t.Fatalf("DeriveDataKey: %v", err)
	}
	if len(got) != 32 {
		t.Fatalf("derived key length = %d, want 32", len(got))
	}
	if gotB64 := base64.StdEncoding.EncodeToString(got); gotB64 != wantB64 {
		t.Fatalf("DeriveDataKey mismatch:\n got  %s\n want %s", gotB64, wantB64)
	}
}

// TestDataKeyRoundTrip confirms a passphrase-derived key encrypts and decrypts
// through the AES-256-GCM layer (the derived key is exactly 32 bytes, so the
// crypto layer's padKey is a no-op on it).
func TestDataKeyRoundTrip(t *testing.T) {
	key, err := DeriveDataKey("hunter2", "AAECAwQFBgcICQoLDA0ODw==", 1000)
	if err != nil {
		t.Fatalf("DeriveDataKey: %v", err)
	}
	ct, err := EncryptWithProjectKey("SECRET=value", string(key))
	if err != nil {
		t.Fatalf("EncryptWithProjectKey: %v", err)
	}
	pt, err := DecryptWithProjectKey(ct, string(key))
	if err != nil {
		t.Fatalf("DecryptWithProjectKey: %v", err)
	}
	if pt != "SECRET=value" {
		t.Fatalf("round-trip got %q, want %q", pt, "SECRET=value")
	}
}

func TestDeriveProjectKeyMatchesWebPadKey(t *testing.T) {
	// 64-char hex key: web takes the first 32 CHARACTERS as ASCII bytes
	// (str_pad then substr(0,32)) — NOT hex-decoded.
	got := DeriveProjectKey("52c7e8f043e61267076c35827d6c4be454c70ecac00bf10e79a56d703e32e123")
	want := []byte("52c7e8f043e61267076c35827d6c4be4")
	if !bytes.Equal(got, want) {
		t.Fatalf("hex64 derive got %q, want %q", got, want)
	}

	// Short key: padded with '0' (0x30) to 32 bytes.
	got2 := DeriveProjectKey("test-key-123")
	want2 := append([]byte("test-key-123"), bytes.Repeat([]byte("0"), 32-len("test-key-123"))...)
	if !bytes.Equal(got2, want2) {
		t.Fatalf("short derive got %q, want %q", got2, want2)
	}
}
